# Generated by Django 4.2 on 2024-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='cover_pictures/default-book.jpg', upload_to='cover_pictures'),
        ),
    ]
