# Generated by Django 4.2 on 2024-07-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='cover_pictures/default-book.jpg', upload_to='cover_pictures'),
        ),
    ]
