# Generated by Django 4.2 on 2024-08-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_bookreview_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
